### ISSUE TITLE
More neutral name

### ISSUE THREAD

**Issue by ai** [jonathantneal/precss#1]
I think, that “Sass” link in name is bad because:

* users will expect Sass behaviour
* we will think only about Sass way instead of have free minds
* it is a bad marketing, because we use Sass trademark for non-Sass ecosystem

**Comment by ai** [comment]
I have plans for same plugin pack and I thought to use **PostCSS Lang** name. Because it is a new language, not CSS.

**Comment by MoOx** [comment]
Here is one idea: postcssor

**Comment by MoOx** [comment]
Another one: precss.

**Comment by jonathantneal** [comment]
**precss**
