### ISSUE TITLE
Request: add dependency on postcss-define-functions

### ISSUE THREAD

**Issue by Mexflubber** [jonathantneal/precss#100]
Can you include https://www.npmjs.com/package/postcss-define-function to PreCss ?

**Comment by doasync** [comment]
Mixins are used instead

**Comment by Mexflubber** [comment]
What If I actually need a function? Like converting px-to-em ?

**Comment by doasync** [comment]
Check this link [https://css-tricks.com/snippets/sass/px-to-em-functions](https://css-tricks.com/snippets/sass/px-to-em-functions)

**Comment by jonathantneal** [comment]
The 2x mixin syntax has been dropped for something closer to Sass. Feel free to make a PR with [postcss-advanced-variables](https://github.com/jonathantneal/postcss-advanced-variables/) if you want to see a Sass functions feature ported over.
