### ISSUE TITLE
Update/add some plugins?

### ISSUE THREAD

**Issue by jpagarcia** [jonathantneal/precss#102]
Use **'postcss-import'** instead of **'postcss-partial-import'**
Use **'postcss-simple-vars'** in addition to **'postcss-advanced-variables'**

**Comment by jonathantneal** [comment]
Unfortunately, postcss-simple-vars doesn’t reasonably allow you to use variables within mixins, extends, conditionals, or loops. However, a new version of postcss-advanced-variables has been released.
