### ISSUE TITLE
Host key verification failed.

### ISSUE THREAD

**Issue by zitengine** [jonathantneal/precss#105]
λ npm install precss --save-dev
npm ERR! Error while executing:
npm ERR! C:\laragon\bin\git\bin\git.EXE ls-remote -h -t ssh://git@github.com/jonathantneal/postcss-font-family-system-ui.git
npm ERR!
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Abhay\AppData\Roaming\npm-cache\_logs\2018-01-17T14_17_40_588Z-debug.log

**Comment by whs** [comment]
It seems that repository is referenced by postcss-preset-env and not this package. I've filed an issue: https://github.com/jonathantneal/postcss-preset-env/issues/2

**Comment by jonathantneal** [comment]
Resolved by https://github.com/jonathantneal/precss/commit/8876377687dd2bf99d13ef22684e63488b6231e5
