### ISSUE TITLE
SyntaxError: Unexpected token import. ☹ Please help me

### ISSUE THREAD

**Issue by dylan-7** [jonathantneal/precss#107]
./src/index.css
Module build failed: I:\demo\test-postcss\node_modules\postcss-preset-env\node_modules\postcss-font-family-system-ui\index.js:2
import postcss from 'postcss';
^^^^^^

SyntaxError: Unexpected token import

**Comment by lcxfs1991** [comment]
Similar to what happened to me. I also mentioned in this issue: https://github.com/jonathantneal/precss/issues/106

**Comment by jonathantneal** [comment]
Resolved by https://github.com/jonathantneal/precss/commit/8876377687dd2bf99d13ef22684e63488b6231e5 and a new version has been published.
