### ISSUE TITLE
Wrong transformation of multiple value css properties (missing space)

### ISSUE THREAD

**Issue by martinkutter** [jonathantneal/precss#109]
Hey, after updating to 3.1, the following happend:

`border-left: 13px solid color-mod(#000 alpha(0.5));`
is transformed to:
`border-left: 13px solidrgba(0, 0, 0, 0.5)`
(see the missing space)

**Comment by leesdolphin** [comment]
So, this is definitely caused by the [`postcss-color-mod-function`](https://github.com/jonathantneal/postcss-color-mod-function) module.

I've created an issue over there jonathantneal/postcss-color-mod-function#5.

**Comment by jonathantneal** [comment]
Thanks for reporting this @martinkutter, and thanks for finding the source of the issue, @leesdolphin

**Comment by leesdolphin** [comment]
Thanks for the quick merge, Would it be possible to bump the `postcss-preset-env` version to 3.x to take advantage of that fix?

**Comment by martinkutter** [comment]
Thank you very much!

**Comment by jonathantneal** [comment]
Patched in 3.1.1. Thanks @leesdolphin !
