### ISSUE TITLE
Importing variables in css

### ISSUE THREAD

**Issue by illiaskh** [jonathantneal/precss#110]
Hello, i'm currently working on my new workflow.
I'm working with postcss and i'm trying to recreate a sass-like environment.
I wanted to get variables in my css so i added Postcss-simple-vars and I want to separate my work into multiple files so i use precss for that. I wanted to import variables from a file to an other but it seems like it doesn't work and i can't get a way around it. 
I really don't want to work with a preprocessor this time but only with Postcss as it is way faster.
Could anyone explain me how to properly import variables?
Thanks in advance

**Comment by doasync** [comment]
You can try to use `postcss-easy-import` plugin (or `postcss-partial-import`) before precss (see issue #112)

**Comment by illiaskh** [comment]
Issue #112 's temporary solution does the work, closing issue
