### ISSUE TITLE
TypeError: Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by andrewMuntyan** [jonathantneal/precss#117]
H, @jonathantneal . Thank you for your work.

Need some hand here.

I'm using webpack and trying to use postCss with precss plugin and it works well until i try to import partial styles with absolute paths.
f.e.
in root folder i have `shared/styles/colors.css`
```javascript
$black: #000000;
```
and `components/component/component.css`
```javascript
@import '../../shared/styles/colors.css';

.selector {
  color: $black
}
```
whit such imports it works just well, but if i try to import with absolute path `@import 'shared/styles/colors.css';` i have an error
```javascript
ERROR in ./src/components/CssModules/styles.css (./node_modules/typings-for-css-modules-loader/lib??ref--6-1!./node_modules/postcss-loader/lib??ref--6-2!./src/components/CssModules/styles.css)
Module build failed: TypeError: Cannot read property 'file' of undefined
    at /Users/andrew/Coding/yet-another-ts-starter/node_modules/postcss-advanced-variables/index.bundle.js:400:21
    at <anonymous>
```
Even with next`.postcss.config.js` i can't get it done: 
```javascript
const { srcDir } = require('./paths');
console.log('srcDir'); // i'm able to see correct path here

module.exports = ctx => ({
  map: ctx.env === 'development' ? ctx.map : false,
  plugins: [
    require('precss')({
      importRoot: srcDir, // does not work
      importPaths: [srcDir], // does not work
      importResolve: (id, cwd, opts) => {
        console.log('id', id); // does not log id to console, so i think it was not even called
        return resolve({ id, cwd });
      },
    }),
    require('autoprefixer'),
  ],
});
```

i saw this issue [Simplifying import paths
](https://github.com/jonathantneal/precss/issues/78), but my `importResolve` is not called i think.

Did i miss smth during configuration process?

You can find [last commit with reproducible example here](https://github.com/andrewMuntyan/yet-another-ts-starter/commit/ced647eae95117ab3fd266f3769e8a3e91fc9e98).
Just clone it, npm i, npm start and go to `src/components/CssModules/styles.css` and change import path from `@import '../../shared/styles/colors.css';` to absolute `@import 'shared/styles/colors.css';`

also i have tried to use composing like 
``` javascript
.root {
  composes: contentBlock from '../../shared/styles/styles.css';
}
```
is there any chance to use absolute path in that case?

**Comment by andrewMuntyan** [comment]
anyway i cant manage correct importing, so have installed `postcss-import` and it solved my issue with absolute imports for css files.

**Comment by tnguyen14** [comment]
I just ran into this issue as well. Had to use `postcss-easy-import` to bypass it.

I think this issue should be re-opened and kept open until the PR is merged/ released.
