### ISSUE TITLE
@content in mixins

### ISSUE THREAD

**Issue by johjacb** [jonathantneal/precss#13]
I've got a mixin like this:

```
@define-mixin respond-min $width {
  @media only screen and (min-width: $width) {@content;}
}
```

The @mixin works, but the @content doesn't come through.

```
@media only screen and (min-width: 60em) {
  @content;
}
```

Is this feature supported? Thanks!

**Comment by etanlubeck** [comment]
@johjacb used @mixin-content;

**Comment by johjacb** [comment]
excellent thank you!

**Comment by johjacb** [comment]
Well - the @mixin-content bit is working, but it appears if I pass a variable to the mixin, it doesn't come through. 

Mixin:
```
@define-mixin respond-min $width {
  @media only screen and (min-width: $width) {@content;}
}
```

Call:
```
@mixin respond-min $large {
// css
}
```

Output:
```
@media only screen and (min-width: $large) {
// css
}
```

**Comment by jonathantneal** [comment]
This is because the mixin plugin doesn’t cooperate with the variables plugin. I’m uncertain how to resolve this issue just yet.

**Comment by Ser-Gen** [comment]
By the way, the @johjacb's example is working now:

```sass
/* input */

$blue: #056ef0;
$large: 2000px;

@define-mixin respond-min $width {
	@media only screen and (min-width: $width) {@mixin-content;}
}

@mixin respond-min $large {
	a {
		color: $blue;
	}
}
```

```css
/* output */

@media only screen and (min-width: 2000px) {
    a {
        color: #056ef0
    }
}
```

**Comment by johjacb** [comment]
that's great! :+1:

**Comment by jonathantneal** [comment]
FWIW this is now a feature https://github.com/jonathantneal/postcss-advanced-variables/#mixin-include-and-content-rules
