### ISSUE TITLE
@extend creating duplicate class with empty declaration

### ISSUE THREAD

**Issue by etanlubeck** [jonathantneal/precss#17]
Here's an interesting problem. Any ideas? Is it because I'm using extend in the class name?

```
/* Extends */
@define-extend bg-green {
  background-color: green;
}

.extend-class {
  @extend bg-green;
}
```

produces an extra .extend-class

```
/* Extends */
.extend-class {
  background-color: green;
}


.extend-class {
}

```

**Comment by jonathantneal** [comment]
PreCSS does not use the `@define-extend` syntax. It uses the `@extend` syntax, which can use placeholder classes like `%bg-green`.
