### ISSUE TITLE
Why not calc like sass?

### ISSUE THREAD

**Issue by songsiqi** [jonathantneal/precss#18]
For example：

Before compile:

```
$column: 200px;
.menu {
    width: 4 * $column;
}
```

After compile:

```
.menu {
    width: 800px;
}
```

**Comment by jonathantneal** [comment]
I think presuming math is a dangerous default. I’d rather see something like `math()` or `$(column * 4)`.

**Comment by Gurylev** [comment]
```
$logo-height: 20px;
$menu-height: 20px;
$header-height: $logo-height + $menu-height + 10px;
```
These variables are not calculated 😰

**Comment by jonathantneal** [comment]
I don’t think there’s a logical reason to believe they should be.

```scss
$header-height: calc($logo-height + $menu-height + 10px);
```

Will [`calc`](https://github.com/postcss/postcss-calc) not due?

**Comment by dbox** [comment]
In sass you have to interpolate the variables. 

``` sass
$header-height: calc(#{$logo-height} + #{$menu-height} + 10px);
```

What is the postcss/precss interpolation syntax?

**Comment by songsiqi** [comment]
I have to use [calc](https://github.com/postcss/postcss-calc) to reduce `calc()`, can `postcss-calc` be packed in `precss` like `postcss-extend`?

**Comment by lkraav** [comment]
I also found `postcss-calc` was the way to go.

**Comment by naykris** [comment]
> width: 4 * $column;

`postcss-automath` calculated this without `calc()`

**Comment by jonathantneal** [comment]
Answered in https://github.com/jonathantneal/precss/issues/98#issuecomment-359530222
