### ISSUE TITLE
Weird errors with version

### ISSUE THREAD

**Issue by herkyl** [jonathantneal/precss#19]
I get an error:
```Your current PostCSS version is 5.0.1, but postcss-advanced-variables uses 4.1.16. Perhaps this is the source of the error below.```

Why is PostCSS a dependency of Precss? Precss required PostCSS 4.1.16 but gulp-postcss requires 5.0.1.

**Comment by jonathantneal** [comment]
I have updated all of the dependencies for both precss and postcss-advanced-variables.

**Comment by herkyl** [comment]
:+1:
