### ISSUE TITLE
Container#eachAtRule is deprecated

### ISSUE THREAD

**Issue by fingermaster** [jonathantneal/precss#21]
I'm noticing this on many of the plugins today:

Container#eachAtRule is deprecated. Use Container#walkAtRules instead.
Node#before is deprecated. Use Node#raws.before
Container#eachDecl is deprecated. Use Container#walkDecls instead.
Fatal error: Cannot read property 'before' of undefined

**Comment by jonathantneal** [comment]
Resolved in 1.0.0 during update to PostCSS 5
