### ISSUE TITLE
Inline comments, postcss-scss and imports

### ISSUE THREAD

**Issue by davidhund** [jonathantneal/precss#24]
Just getting into PostCSS and puzzled by the lack of support for inline comments.

`// Like this one…`

This Sass feature is sorely missed from precss.

So @ai advised using the `postcss-scss` parser which deals with single-line ('inline') comments.
However, while postcss-scss alone deals with those comments fine (converts to `/* .. */`) adding precss  breaks them again. (I have an inline comment in a partial file that's imported in my main stylesheet.)

Two questions:

- Have you considered precss support for inline comments?
- Do you have any idea on why postcss-scss no longer works with precss?

**Comment by ai** [comment]
@davidhund PreCSS is a plugin to transform CSS. So it do not have deal with syntax, because in PostCSS plugins can change a parser.

But we can add some examples of using SCSS syntax to get inline comment to PreCSS docs.

**Comment by davidhund** [comment]
Thanks for all your quick replies @ai — and excuse me for asking so many questions. I guess I'm still a bit confused as to how PostCSS etc. is supposed to work…

I'm afraid I do not completely understand your first line: are you saying that PreCSS is not supposed to be able to work when I add a custom parser?

I thought postcss-scss simply converted inline comments to standard ones, and _then_ PreCSS could pick those up…

Anyway: some examples of working with SCSS syntax (and inline comments) would be great!

**Comment by davidhund** [comment]
FYI: After chatting about this issue on https://gitter.im/postcss/postcss it seems the issue lies with `postcss-import` (and not PreCSS per se).

It seems postcss-import creates a a PostCSS processor and does not take the custom Parser into account when importing stylesheets.

https://github.com/postcss/postcss-import/blob/master/index.js#L83-L90

Apparently it's a trivial fix so I'll figure out a way to work around the inline comments for the moment. I'm hoping postcss-import will be fixed soon so that PreCSS can be updated and inline comments will work in imported stylesheets.

**Comment by jonathantneal** [comment]
@davidhund, I have moved from postcss-import to [postcss-partial-import](https://github.com/jonathantneal/postcss-partial-import) which forwards plugins and syntax, and allows for Sass-like partial imports.

**Comment by davidhund** [comment]
@jonathantneal Cool!
So this means inline comments in imported partials will be handled correctly (because the `scss` parser is forwarded/used)?

I'll test it soon. Thanks.

**Comment by AntonioRedondo** [comment]
6 years later and this thing is still biting hard!

For reference: https://github.com/csstools/precss/issues/81

**Comment by DaveyJake** [comment]
> 6 years later and this thing is still biting hard!
> 
> For reference: #81

I'm experiencing this very issue, myself, right now.  Definitely still a headache!
