### ISSUE TITLE
Grunt fails: "ReferenceError: Promise is not defined"

### ISSUE THREAD

**Issue by adekbadek** [jonathantneal/precss#26]
I'm just starting with PostCSS (using Grunt), so maybe I'm doing something wrong, but:
1. Grunt throws an error when I try to run task involving PreCSS: "ReferenceError: Promise is not defined"
2. When line "require('precss')()" is commented out, grunt works
3. I checked with the version 0.3.0 and it's working, problem is with 1.0.0

**Comment by jonathantneal** [comment]
This is because PreCSS 1 and PostCSS 5 require a newer version of node. 

If you want to run PostCSS on node.js 0.10, add a Promise polyfill:

```js
require('es6-promise').polyfill();
var postcss = require('postcss');
```
