### ISSUE TITLE
Add postcss-atroot plugin

### ISSUE THREAD

**Issue by OEvgeny** [jonathantneal/precss#31]
[OEvgeny/postcss-atroot](https://github.com/postcss/postcss)
The ``@at-root`` causes one or more rules to be emitted at the root of the document, rather than being nested beneath their parent selectors:
```css
.parent {
  ...
  @at-root{
    .child {...}
  }
}
```
Which would produce:
```css
.child { ... }
.parent { ... }
```

**Comment by jonathantneal** [comment]
I actually would like to add this in.

**Comment by jonathantneal** [comment]
Added!

**Comment by OEvgeny** [comment]
@jonathantneal Thanks, let me know if something goes wrong with this :+1:
