### ISSUE TITLE
How to set options plugin options (Better Documentation)?

### ISSUE THREAD

**Issue by elimc** [jonathantneal/precss#34]
I have managed to get PreCSS working and I'm pretty stoked about it. However, the documentation is not very clear on how to set options working. For example, I want to set the `postcss-partial-import` to use the .scss extension, so that my IDE can recognize SASSy code. How would I go about setting this option?

This is my current setup:

``` js
gulp.task('sass', function() {
    var processors = [
        precss,
        lost,
        autoprefixer({
            browsers: ['last 2 versions', 'ie 9', 'android 2.3', 'android 4'],
            cascade: false
        }),
        mqpacker,
        csswring
    ];
    return gulp.src(sassSource)
        .pipe(sourcemaps.init())
        .pipe(postcss(processors))
        .pipe(sourcemaps.write('./'))
        .pipe(gulp.dest(sassDestination))
        .pipe(browserSync.stream());
});
```

I'm assuming it would be some thing like the following?

``` js
gulp.task('sass', function() {
    var processors = [
        precss( postcss-partial-import )({ extension: 'scss' }),
        lost,
        autoprefixer({
            browsers: ['last 2 versions', 'ie 9', 'android 2.3', 'android 4'],
            cascade: false
        }),
        mqpacker,
        csswring
    ];
    return gulp.src(sassSource)
        .pipe(sourcemaps.init())
        .pipe(postcss(processors))
        .pipe(sourcemaps.write('./'))
        .pipe(gulp.dest(sassDestination))
        .pipe(browserSync.stream());
});
```

But I have no clue. Please help.

**Comment by ichabodcole** [comment]
I believe you would some something like the below, passing in an object with a key that is the name of the plugin you are targeting and a value which is an object setting the options for that plugin. If you check out the precess index.js file you will see the list of plugins with a namespace attribute that is the key the plugin is exposed as, and which can be used as a reference to set options like the below example.

    precss({ postcss-partial-import: { extension: 'scss' }})

**Comment by elimc** [comment]
@ichabodcole Just tested and can confirm that this seems to work. Thanks so much. I would definitely recommend including this documentation.

**Comment by BrianSipple** [comment]
+1

**Comment by lkraav** [comment]
This also confused me, but happy to report everything works with `postcss-cli` as well.

postcss.json

```
{
  "precss": {
    "import": {
      "extension": "scss"
    }
  }
}

**Comment by jonathantneal** [comment]
The plugin has changed so much since this issue was filed, I hope the current documentation is of higher quality: https://github.com/jonathantneal/precss

**Comment by Romancho** [comment]
> The plugin has changed so much since this issue was filed, I hope the current documentation is of higher quality: https://github.com/jonathantneal/precss
Excuse me, but:
Where is HQ documentation? 
`precss(/* options */)` 
What`s `options`? How to change default extention for Gulp/Webpack/Grunt?
I just see how to use npm & routine includes config
