### ISSUE TITLE
Run operations on variables

### ISSUE THREAD

**Issue by Jonjoe** [jonathantneal/precss#35]
Absolutely loving precss but i'm starting to feel a pang in my heart for variable operations.

For example
```
$gap:15px;
.somthing {
   margin:$gap/2;
}
```

or

```
$gap:15px;
$ubergap:$gap*2;
```
Couldn't find the in the docs and when i try this the css is outputted unprocessed. 

Any help? <3

**Comment by jonathantneal** [comment]
PreCSS prefers explicit math. This would be a use-case for `calc`.

```css
margin: calc($gap / 2);
```

**Comment by jonathantneal** [comment]
Closing as duplicate of #18
