### ISSUE TITLE
Removed ; and extra new lines

### ISSUE THREAD

**Issue by marlass** [jonathantneal/precss#42]
When i use postcss with precss as only plugin on file style.css which contains only `@import "generic/normalize"` precss adds extra new lines between properties and removes semicolon after last property.
Example (genereic/normalize.css):

```
.test{
height: 10px;
width: 10px;
}
```

Dest:

```
.test{

height: 10px;

width: 10px
}
```

When you add some css in style.css (example: `html{background: white;}`) it fixes both problems. But if you skip semicolon after last rule (example: `html{background: white}`) it only fixes extra new lines.

**Comment by jonathantneal** [comment]
PostCSS manages the commas, and not this plugin.
