### ISSUE TITLE
Property lookup is gone

### ISSUE THREAD

**Issue by pawelphilipczyk** [jonathantneal/precss#47]
There's an example of usage for postcss-property-lookup plugin but looking at the npm package.json I can't see it and of course the example is not working either. Is this replaced by something else or just an error in the README?

**Comment by vyorkin** [comment]
The same, property lookup doesn't work for me

**Comment by Ser-Gen** [comment]
@pawelphilipczyk, @vyorkin, now it should be working: version `1.4.0` is released on [npm](https://www.npmjs.com/package/precss).

Will be nice to see this version here, on Precss [releases](https://github.com/jonathantneal/precss/releases).

**Comment by jonathantneal** [comment]
Thanks @Ser-Gen (a very, very delayed thanks)
