### ISSUE TITLE
missing a trailing semicolon

### ISSUE THREAD

**Issue by aspanoz** [jonathantneal/precss#48]
/\* before */

.notice--clear {
    @if 3 < 5 {
        background: green;
    }
    @else {
        background: blue;
    }
}

/\* after */

.notice--clear {
    background: green
}

**Comment by RegisBiron** [comment]
I'm experiencing this issue as well. For reference I'm also using `@import`. This happens for the entire transformed css. Here is an example of normalize.css 

```
/*! normalize.css v3.0.3 | MIT License | github.com/necolas/normalize.css */

	/**
 * 1. Set default font family to sans-serif.
 * 2. Prevent iOS and IE text size adjust after device orientation change,
 *    without disabling user zoom.
 */

	html {
    font-family: sans-serif;/* 1 */
    -ms-text-size-adjust: 100%;/* 2 */
    -webkit-text-size-adjust: 100%/* 2 */
}

	/**
 * Remove default margin.
 */

	body {
    margin: 0
}
```

In the interim I found that if I use a nested parent selector, it seems to fix the issue and the semicolons are added back in. 

```
/* before */
.test {
  padding: 10px;
  &::after {
    padding: 10px;
  }
}

/* after */
.test {
    padding: 10px;
}

.test::after {
    padding: 10px;
}
```

**Comment by jonathantneal** [comment]
Commas are normalized by PostCSS and not this plugin.
