### ISSUE TITLE
Linking Bootstrap's Sass code

### ISSUE THREAD

**Issue by brandon-arnold** [jonathantneal/precss#49]
I'm having trouble linking Bootstrap's Sass code as per [this example](http://jonathanmh.com/bootstrap-4-grid-only-and-sass-with-gulp/) (grid-only, version 4-alpha2). The dependency is acquired correctly into `node_modules/` and I added the 7 lines into my scss file. And the `/\.scss$/` section of my webpack config is as such: 

``` javascript
//module.loaders: [...
{
  test: /\.scss$/,
  loaders: [
    'isomorphic-style-loader',
    'css-loader?' + (DEBUG ? 'sourceMap&' : 'minimize&') +
    'modules&localIdentName=[name]_[local]_[hash:base64:3]',
    'postcss-loader',
  ],
}, //...
```

But when I try to build, the isomorphic style loader complains with errors in Bootstrap. One line for example seems to be trying to evaluate a comment, because it says 'Unclosed quote' on a line in the Bootstrap code file that has a quote, but is in a comment. Apparently the postcss-loader doesn't recognize Sass single-line comments, at the very least. 

Here is my postcss section of the webpack config: 

``` javascript
  postcss: function plugins(bundler) {
    return [
      require('postcss-import')({ addDependencyTo: bundler }),
      require('precss')(),
      require('autoprefixer')({ browsers: AUTOPREFIXER_BROWSERS }),
    ];
  }
```

Short of asking for a pull request for PreCSS to support single-line comments, can anyone suggest a way for me to get this to work?

**Comment by jordanh** [comment]
I'm creating a similar webpack configuration for a project I'm working on. I think the way forward is to wire up precss to use the postcss-scss parser, but I'm not quite certain how to do this within webpack. See: https://github.com/postcss/postcss-scss

Note, "this module also enables parsing of single-line comments in CSS source code."

**Comment by jordanh** [comment]
Ah! I think I got it. From the loader docs: https://github.com/postcss/postcss-loader

```javascript
        // In your webpack configuration...
        // ...
        {
          test: /\.css$/,
          loader: 'style-loader!css-loader!postcss-loader?parser=postcss-scss'
        },
       // ...
```

Note the 'parser=postcss-scss' there...

Hopefully that will work for you!

**Comment by dfrankland** [comment]
@brandon-arnold I fixed that exact problem with this pull request: https://github.com/kriasoft/react-starter-kit/pull/384

**Comment by brandon-arnold** [comment]
Hey there, @dfrankland:

Nice, thanks for the response. I'm not quite there. I had actually already tried the ```?parser=postcss-scss``` and had still gotten the comment error, but your region from the Webpack config in your pull request: 

```javascript
transform: contents => contents.replace(
            /\/\*[^~]*?\*\/|\/\/(.*)/g,
            '/*$1*/'
          )
```

fixes this. 

For what it's worth I'm not quite there yet. Still learning Webpack to be honest. Now it's having trouble  not finding the subdirectory of ```node_modules/bootstrap/scss``` that is being imported in ```_mixins.scss```. This file from Bootstrap has imports to the subdirectory ```mixins``` that my build is trying to locate relative to the root of the project, viz:

```bash
ERROR in ./~/css-loader?sourceMap&modules&localIdentName=[name]_[local]_[hash:base64:3]!./~/postcss-loader?parser=postcss-scss&pack=compile!./~/postcss-loader?pack=import!./src/components/ContentPage/ContentPage.scss
    Module build failed: Error: C:\path\to\project\node_modules\bootstrap\scss\_mixins.scss:18:1: Failed to find 'mixins/breakpoints' from C:\path\to\project
        in [
            C:\path\to\project\node_modules\bootstrap\scss,
            C:\path\to\project\src\components,
            C:\path\to\project\src\components\ContentPage
        ]
```

I tried various ways of including the path in the webpack config. Still fighting with it.

```javascript
{
        test: /\.scss$/,
        include: [
          path.resolve(__dirname, '../src'),
          path.resolve(__dirname, '../node_modules/bootstrap/scss'),
          path.resolve(__dirname, '../node_modules/bootstrap/scss/mixins'),
        ],
        loaders: [
          'isomorphic-style-loader',
          'css-loader?' + (DEBUG ? 'sourceMap&' : 'minimize&') +
          'modules&localIdentName=[name]_[local]_[hash:base64:3]',
          'postcss-loader?parser=postcss-scss&pack=compile',
          'postcss-loader?pack=import',
        ],
      }
```

**Comment by dfrankland** [comment]
I have spent lots of time trying to get PreCSS to compile Bootstrap v4, but never got it to work because of the way mixins are handled. In normal scss you can `@include` and use the mixin, but PreCSS requires you to `@import` then use `@mixin`. This causes a recursive loop when trying to compile Bootstrap with PreCSS because `_mixins.scss` has mixins that other mixins it imports require (confusing right?). I eventually switched to `sass-loader` because it is just not possible without lots of hacking.

This is the furthest I got if you want to take it any further:
```js
import: [
        require('postcss-import')({
          addDependencyTo: bundler,
          glob: true,
          transform: contents => {
            let transformed = contents;

            // Single line comments
            transformed = transformed.replace(/\/\*[^~]*?\*\/|\/\/(.*)/g, '/*$1*/');

            // String interpolation
            transformed = transformed.replace(/#{\$(.*?)}/g, '$($1)');

            // define mixins and params
            transformed = transformed.replace(
              /@(include|mixin) (.*)\((.*)\) {/g,
              '$1 $2 $3 {'
            );
            transformed = transformed.replace(
              /@include (.*?)\((.*)\);/g,
              '@include $1 $2;'
            );
            transformed = transformed.replace(/@mixin/g, '@define-mixin');
            transformed = transformed.replace(
              /@include/g,
              //'@import "./*.scss"; causes recursive loop
              '@mixin'
            );
            transformed = transformed.replace(/@content/g, '@mixin-content');

            return transformed;
          },
        }),
      ],
```

**Comment by brandon-arnold** [comment]
Is it possible to configure webpack to use both or is it one or the other? I tried to have two sections that test on ```scss```, with one of them having the bootstrap directories in the ```include: [...]``` section and using sass-loader. Webpack seemed to ignore that section no matter what i did. It didnt help to have them in an ```exclude: [...]``` section of the postCss loader config, either.

**Comment by jonathantneal** [comment]
I’m closing this after a lot of inactivity.
