### ISSUE TITLE
incorrect property order in 1.4.0

### ISSUE THREAD

**Issue by MikitaLisavets** [jonathantneal/precss#50]
After update to version 1.4.0 this code:

```
.icon {
  &.active {
    height: 1px;
  }
  &.small {
    height: 2px;
  }
}
```

compiled in:

```
.icon.small {
    height: 2px;
}
.icon.active {
    height: 1px;
}

```

_bug from last version of postcss-nesting plugin_

**Comment by kallaspriit** [comment]
I can confirm this issue, installing previous version of postcss-nesting fixes this temporarily until a proper fix is introduced.

    npm install postcss-nesting@2.0.6 --save

**Comment by AntonioRedondo** [comment]
As another temporary solution you can also use `"precss": "1.3"` on your `package.json` so that there is no need for a global installation and the fix can be committed and spread among a team.

**Comment by jonathantneal** [comment]
Updated postcss-nesting to 4.0.1
