### ISSUE TITLE
Wrong location of comment of the last declaration in a nested rule definition

### ISSUE THREAD

**Issue by songsiqi** [jonathantneal/precss#53]
For example:

```
.a {
  prop1: val1;
  prop2: val2; /*comment*/
  .b {
    prop3: val3;
  }
}
```

should output

```
.a {
  prop1: val1;
  prop2: val2; /*comment*/
}
.a .b {
  prop3: val3;
}
```

But now the output result is:

```
.a {
  prop1: val1;
  prop2: val2;
}
/*comment*/
.a .b {
  prop3: val3;
}
```

I'm not sure whether it's a bug of `postcss-nested` or `postcss-nesting`.

**Comment by whidy** [comment]
我在用px2rem的时候也发现这个问题了.不知道楼主现在有没有解决方案,

**Comment by jonathantneal** [comment]
It’s not possible to know which part it belongs to. It seems to because there are no newlines in the comment, but I think this would sooner be an issue for the PostCSS parser.
