### ISSUE TITLE
Preprocessor like comment block

### ISSUE THREAD

**Issue by ariona** [jonathantneal/precss#55]
Is there any preprocessor like comment, so it will not be rendered in compiled version?

**Comment by stevenvachon** [comment]
Sass/SCSS does not strip them either. Just use a css minifier like [cssnano](https://npmjs.com/cssnano).

**Comment by ismamz** [comment]
@ariona You can use [postcss-strip-inline-comments](https://github.com/mummybot/postcss-strip-inline-comments).

**Comment by jonathantneal** [comment]
^ this seems resolved.
