### ISSUE TITLE
Precss not compatible with your operating system or architecture.  Windows 10 64bit.

### ISSUE THREAD

**Issue by matthewharwood** [jonathantneal/precss#57]
Just flagging this. Precss isn't compatible with windows. Curious if this is happening to everyone or just me?  I have linux and Mac I can try there too.

npm install --save-dev precss
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.7
npm WARN Morningharwood@1.0.0 No description

**Comment by matthewharwood** [comment]
https://github.com/npm/npm/issues/9204 Pretty sure this fixed it.

**Comment by uharbachou** [comment]
I'm not sure is this actual. win10 x64 installed precss and it works.

**Comment by jonathantneal** [comment]
Thanks @matthewharwood, @ghost
