### ISSUE TITLE
Mixin @content Support

### ISSUE THREAD

**Issue by RyoIkarashi** [jonathantneal/precss#58]
In Sass you are able to pass in arbitrary content into a mixin with the @content directive.

Is there a way to accomplish this now? Plans to support it?

**Comment by Vpr99** [comment]
@RyoIkarashi I think `@mixin-content;` is what you're looking for. Since PreCSS uses [postcss-mixins](https://github.com/postcss/postcss-mixins) you can check out all the docs there.

**Comment by RyoIkarashi** [comment]
Thank @Vpr99!
