### ISSUE TITLE
Existence of argument in mixin conditional?

### ISSUE THREAD

**Issue by kkomaz** [jonathantneal/precss#64]
Just curious what the proper syntax would be to check if an argument in a mixin function exists.  For example I am currently checking if one my argument is **not** a null value but I'm not a big fan...

```
@define-mixin size $width, $height: null {
  @if $height != null  {
    height: $height;
  }
}
```

Ideally I would love to do something like

```
@define-mixin size $width, $height: null {
  @if $height  {
    height: $height;
  }
}
```

**Comment by jonathantneal** [comment]
PreCSS v3 does not use the non-sass-like `@define-mixin`.
