### ISSUE TITLE
Add support for rgba(#aaaaaa, 0.4) with postcss-hexrgba

### ISSUE THREAD

**Issue by bfred-it** [jonathantneal/precss#67]
Sass transforms `rgba(#000, 0.4)` to `rgba(0, 0, 0, 0.4)`. This feature can be added with https://github.com/seaneking/postcss-hexrgba

**Comment by jonathantneal** [comment]
I’m open to a PR for this, but it would be hard to know where it should go in the plugin order. Probably before postcss-color-mod-function?

This could also be done this way:

```css
test {
  color: color-mod(black a(4%));
}
```

Which seems very readable to me.
