### ISSUE TITLE
Silently fails on some syntax errors

### ISSUE THREAD

**Issue by fastfedora** [jonathantneal/precss#74]
Syntax errors are often not caught and reported when using precss.

For instance, multi-line import statements fail silently with only the first file being imported:

```
@import "abstracts/fonts",
        "abstracts/colors";
```

These are supported in Saas, but apparently not by the `postcss-partial-import` plugin.

I've run into the issue with other types of statements too. I have to just guess what went wrong.

This may not be an issue that precss can solve, since it is a collection of other plugins, each with their process for handling errors, but I thought it worth noting for others. A linter that can handle all the syntaxes that precss supports might solve the problem.

I had hoped to use precss instead of Saas, but for now am switching over to Saas to get the error handling I need for debugging.

**Comment by djforth** [comment]
+1

**Comment by jpagarcia** [comment]
experiencing this problem as well

**Comment by jonathantneal** [comment]
This is not behavior I have seen recommended before in Sass. I’m open to a PR to [PostCSS Advanced Variables](https://github.com/jonathantneal/postcss-advanced-variables/) to add it. It wouldn’t be added here to PreCSS.

**Comment by fastfedora** [comment]
What behavior do you mean being not recommended: the specific syntax I used as an example or the behavior of reporting syntax errors?  This issue is specifically about syntax errors not being reported, not the syntax I used as an example. Saas does report syntax errors that it finds.
