### ISSUE TITLE
Variable interpolation in @extend

### ISSUE THREAD

**Issue by goodsoft** [jonathantneal/precss#75]
Variables are not interpolated in extend rules.

Example:

```
$color: green;

%bg-green {
    background-color: green;
}

.notice {
    @extend %bg-$color;
}
```

Expected output:

```
.notice {
    background-color: green;
}
```

Actual output: none.

**Comment by ThiagoFacchini** [comment]
It's being a while since posted.

Any fix or workaround?

**Comment by jonathantneal** [comment]
There is no work-around for this, as PostCSS Extend (for the extend) and PostCSS Advanced Variables (for the variables) can’t run at the same time. This is an issue at the plugin architecture level with PostCSS.
