### ISSUE TITLE
Simplifying import paths

### ISSUE THREAD

**Issue by nareshbhatia** [jonathantneal/precss#78]
I am looking to simplify the imports of my frequently used partials. These partials are stored in a central place, e.g. `/core/styles`. An import statement may look like this:

```
@import '../../../core/styles/colors';
```

Is there any way to tell precss that all my partials are at `/core/styles` and thus simplify the above statement as:

```
@import 'colors';
```

**Comment by eduardoleal** [comment]
Any luck on this?

**Comment by brandonheyer** [comment]
You'll want to write a custom resolver, something like this, which only adds the prefix for files that aren't `main.scss`. Note though ,that this bypasses the default 1postcss-partial-import` behavior, you can use that resolve-id if you prefer, but I found it just caused issues

```
var resolveId = require('postcss-import/lib/resolve-id');

postcss([
  precess({
    resolve: function(id, base, options) {
      var parts = id.split('/');

      if (parts[parts.length - 1] === 'main') {
        parts[parts.length - 1] = parts[parts.length - 1] + options.extension; 
      } else {
        parts[parts.length - 1] = options.prefix + parts[parts.length - 1] + options.extension;
      }

      return resolveId(parts.join('/'), base, options);
    },
    // glob: false,
    prefix: '_',
    extension: '.scss'
  })
])
```

**Comment by nareshbhatia** [comment]
Thanks, @brandonheyer. That's very helpful.
