### ISSUE TITLE
Official file extension 

### ISSUE THREAD

**Issue by ai** [jonathantneal/precss#8]
Mayb we should select official file extension for PreCSS source (or any PostCSS sources with custom CSS).

What about `.pcss`?

**Comment by hudochenkov** [comment]
I like `.pcss`. With official file extension for all CSS contains PostCSS stuff it will be easier for editors and other tools to detect syntax highlighting and other syntax related things.

@ai, maybe you should open this issue in [postcss/postcss](https://github.com/postcss/postcss/)?

**Comment by ai** [comment]
@hudochenkov cssnext or autoprefixer doesn’t need any file ext because they work with plain CSS.

**Comment by hudochenkov** [comment]
@ai but many other plugins doesn't W3C standards compatible.

**Comment by ai** [comment]
@hudochenkov what plugins you can remember outside the PreCSS? ;)

**Comment by hudochenkov** [comment]
Just a few :)

https://github.com/whitneyit/postcss-strip-units
https://github.com/simonsmith/postcss-property-lookup
https://github.com/daleeidd/postcss-define-property
https://github.com/antyakushev/postcss-for
https://github.com/outpunk/postcss-each
https://github.com/seaneking/postcss-alias

**Comment by ai** [comment]
@hudochenkov each and for is in PreCSS, other should be moved there too.

**Comment by jedmao** [comment]
@ai if these plugins can be parsed by a CSS parser, then, in a way, are they not valid CSS? In other words, what exactly do we mean by valid CSS?

**Comment by jedmao** [comment]
Also, @ai, did you anticipate this happening with PostCSS plugins or does this deviate, somehow, from the original project scope? I'm just curious what your philosophy is here.

**Comment by ai** [comment]
Technically, custom at-rule is not part of W3C CSS. File is still valid, but content of this at-rule will be ignored.

**Comment by jonathantneal** [comment]
I’m not convinced a custom syntax is warranted. I’d rather see a plugin for Sublime or Atom that uses PostCSS to handle the formatting, agnostic to precss.
