### ISSUE TITLE
Simple functions instead of mixins

### ISSUE THREAD

**Issue by PierrickGT** [jonathantneal/precss#80]
I love to use PreCSS but one thing that bother me is that I can only use mixins and not functions like I used to with SASS.

For example, I'd like to use this kind of function :

```
$browser-context: 16; // Default

@function em($pixels, $context: $browser-context) {
  @return #{$pixels/$context}em;
}
```

So I can write the following CSS :

```
h1 {
  font-size: em(32);
}
```

Instead, I have to use the following mixin : 

```
@define-mixin font-size $px {
  font-size: calc($px/16)em;
}
```

And write the following CSS : 

```
h1 {
  @mixin font-size 32;
}
```

But if I want to convert px to em for let's say a `padding-top`, I'll have to define a new mixin specifically for `padding-top`... Pretty redondant and time consuming.

Does anyone know a PostCSS plugin or any workaround that could help me write this kind of reusable SASS function?

**Comment by dubstrike** [comment]
+1

I'm also missing function support and haven't found a plugin for it yet.

**Comment by PierrickGT** [comment]
I've found a temporary solution that fulfill my needs by using the [postcss-functions](https://github.com/andyjansson/postcss-functions) plugin.

I've written the following function:
```
var postCssFunctions = functions({
  functions: {
    em: function(pixels) {
      var browserContext = 16;
      var pixels = parseInt(pixels, 10);
      return pixels/browserContext;
    }
  }
});
```

That I use this way in my CSS code:
```
.l-help {
    box-sizing: content-box;
    padding: em(36)rem em(10)rem em(12)rem;
  }
```

And it outputs the following CSS code:
```
.l-help {
    box-sizing: content-box;
    padding: 2.25rem 0.625rem 0.75rem;
}
```

To make use of the following function, my Gulp task if the following:
```
gulp.task('css', function() {
  var processors = [precss, postCssFunctions, cssnext, assets({
    basePath: 'public/',
    loadPaths: ['assets/images/**']
  }), browserReporter, reporter, cssnano({autoprefixer: false, zindex: false})];
  return gulp.src('./source/css/style.css')
  .pipe($.sourcemaps.init())
  .pipe($.postcss(processors))
  .pipe($.sourcemaps.write('.'))
  .pipe(gulp.dest('./public/assets/stylesheets'))
  .pipe(browserSync.stream());
});
```

I'll let you know if I find a solution to write those functions directly in the CSS code.

**Comment by wdanilo** [comment]
Hi! Is there any progress regarding this issue? Will it be possible to define custom functions from within CSS in PreCSS ?

**Comment by hawckins** [comment]
I am also looking for postcss plugin to resolve this exiting sass function issue.
