### ISSUE TITLE
"Inline" comments

### ISSUE THREAD

**Issue by jmeas** [jonathantneal/precss#81]
One of my favorite features of Stylus are the inline comments.

```styl
// hello
.thing {
  color: #fff;
}
```

Is there any interest in adding support for these in precss?

**Comment by jmeas** [comment]
Gonna close – it seems postcss-scss is the recommended plugin for this functionality.

**Comment by AlexWayfer** [comment]
> Gonna close – it seems postcss-scss is the recommended plugin for this functionality.

They are different plugins… I think PreCSS can have inline comments too, as Sass and Stylus.
