### ISSUE TITLE
Update postcss-partial-import

### ISSUE THREAD

**Issue by lowmess** [jonathantneal/precss#83]
Newer versions of `postcss-partial-import` allow you to (more easily) import stylesheets from `node_modules`. It would be great to see this functionality present in `precss`, unless there was a specific reason it was left out.

**Comment by contentjet** [comment]
+1

**Comment by yuchuanxi** [comment]
+1

**Comment by Puritanic** [comment]
+1!

**Comment by jonathantneal** [comment]
Updated to postcss-partial-import 4.1.0
