### ISSUE TITLE
Status of this project?

### ISSUE THREAD

**Issue by corysimmons** [jonathantneal/precss#84]
Few old PRs open, lots of Issues. If you're not interested in maintaining it, do you care to add someone as a maintainer?

Not trying to whine/demand, just curious.

**Comment by andrewmclagan** [comment]
Not sure about others although we have decided to migrate to CSSNext for a number of reasons:

* This repo has little-to-no maintenance 
* CSSNext will be standards compliant
* node-sass does not support alpine linux and does not look like it will anytime soon.

What are the experiences of others?

**Comment by corysimmons** [comment]
I've just been doing a `node-sass -> css -> postcss` workflow. Gives me the best of both worlds and they're both fast so the extra 10ms or whatever doesn't really kill my soul or anything.

**Comment by PierrickGT** [comment]
I would also go with CSSNext for my next projects with PostCSS in order to be standard compliant.
I've also heard some people are using node-sass with PostCSS and the only reason I would use this kind of workflow is if I needed to write a lot of functions.
For now, [postcss-functions](https://github.com/andyjansson/postcss-functions) works well for me.

**Comment by corysimmons** [comment]
I really don't understand the standard-compliant argument. Preprocessors offer a _lot_ of sugar that even cssnext doesn't.

You can use PostCSS plugins to cover _some_ of these situations, but it's a PITA to know which ones to load and if they've been included on a project or not. That was the entire point of PreCSS -- to load a large collection of those automatically so you didn't have to think about it.

https://medium.com/@Rich_Harris/small-modules-it-s-not-quite-that-simple-3ca532d65de4#.r87t7xsuo

I <3 being able to nest stuff, slap together some stupid mixin, etc., in a predictable/intuitive manner without having to make sure I've loaded 20 modules, so `preprocessor -> css -> postcss plugins -> css` is still my goto. If SugarSS gets more attention, I might switch over.

To each their own, but I've always wondered what the appeal of this migration back to semi-vanilla css is all about...

**Comment by andrewmclagan** [comment]
From my understanding the migration is due to CSS catching up and the standards near completion. Although saying that I do agree with you on many points.

**Comment by prp-e** [comment]
I read a tweet about this project and it seems that it needs a maintainer. If you're looking for a maintainer, I can maintain the project.

**Comment by corysimmons** [comment]
@prp-e I'm sure Jonathan would be up for that. Why not make some quality PRs first then ask for collab?

**Comment by jonathantneal** [comment]
I am up for that. Make some PRs. You’ll find yourself getting maintainer status. I’m cleaning up the repository this morning so it’s easier for new contributors.

**Comment by wdanilo** [comment]
Hi! To sum everything up, is this project dead? I understand that CSSNext brings us some "future" possibilities, but it doesn't replace a good pre-processor. PreCSS seems like the most feature rich pre-processor for PostCSS currently available, but it still lacks many important functionalities, like custom function definitions and there is a lot of bugs to be fixed. I'm just asking if there are any active contributors that will make this project shine? :)

**Comment by corysimmons** [comment]
@wdanilo Read the short thread. Or in summary: maintaining dozens of PostCSS modules that recreate Sass syntax isn't fun/rewarding and doesn't make a lot sense since node-sass exists.

Make your pipeline like this: `input.scss -> node-scss -> sassed.css -> postcss -> final.css`

Someone is more than welcome to take over this project, but in order to take over a project people _have_ to submit a few quality PRs to gain the trust of the original author (and the community).

Feel free to. Orrrrrrr just use that pipeline I just listed.

**Comment by jonathantneal** [comment]
> I am up for that. Make some PRs. You’ll find yourself getting maintainer status. I’m cleaning up the repository this morning so it’s easier for new contributors.

Not many people took me up on this offer. That being said: PreCSS v3 has been released.

**Comment by corysimmons** [comment]
tbh I've been using cssnext + postcss-apply lately and it's been a pretty solid replacement (nesting, vars, etc.)

**Comment by jonathantneal** [comment]
@corysimmons, I was a big fan of postcss-apply until [Tab Atkins explained why it is deprecated](https://www.xanthir.com/b4o00). The status of the PostCSS plugin has also been updated to reflect this: https://github.com/pascalduez/postcss-apply#web-platform-status

FWIW, here’s a list I’m assembling of emerging web features and their position in becoming a web standard: https://jonathantneal.github.io/css-db/

**Comment by corysimmons** [comment]
Yeah I'm aware it got deprecated. Reading why is time consuming. All I know is I like to reuse styles. On a recent project I also missed mixins.

I think maybe postcss-mixins can fix both things though. So cssnext + postcss-mixins = the way?
