### ISSUE TITLE
Interpolation

### ISSUE THREAD

**Issue by GriNAME** [jonathantneal/precss#87]
Can you make this thing

```
$name: border

p.#{$name}
  #{$name}-color: blue
```

The CSS I get out of it is this

```
p.border
  border-color: blue
```

It will be very useful. For example we can use an array of there 

```
$name: border, background

p.#{$name}
  #{$name[1]}-color: blue
```

or associative arrays

```
$name: bd: border,
       bg: background

p.#{$name}
  #{$name.bd}-color: blue
```

**Comment by jonathantneal** [comment]
You could make a PR to [PostCSS Advanced Variables](https://github.com/jonathantneal/postcss-advanced-variables/) that I could review, but I could get to this.
