### ISSUE TITLE
postcss-mixins: version bump to "^5.4.1"?

### ISSUE THREAD

**Issue by lkraav** [jonathantneal/precss#90]
`postcss-mixins-2.1.0` is quite outdated and there's work-stopping bugs. @jonathantneal you think `precss-1.4.1` would be possible?

Not that other libraries don't need version bumps (see #85), but I understand interest in this tool has faded. Perhaps just these cheap small maintenance bumps could still be done? It takes time to move projects to `postcss-cssnext`, perhaps we could figure something out here for the transition period.

**Comment by jonathantneal** [comment]
I’ve updated it to postcss-mixins 6.0.1

**Comment by lkraav** [comment]
@jonathantneal yeehaw :) thanks. Is there supposed to be a new version visible in the GH Releases list?

**Comment by lkraav** [comment]
@jonathantneal indeed, npmjs already shows 2.0.0, but I'm not sure if it picks things up from git tags or `package.json`. Perhaps you could push a new release for github, as well?
