### ISSUE TITLE
Mathematics section

### ISSUE THREAD

**Issue by ai** [jonathantneal/precss#91]
Right now docs miss few things:

1. Some new developers may not know that `calc()` is well supported.
2. Math was one of Sass feature. Users will open a PreCSS docs, will not find Math in features sections and decided that PreCSS is not 100% good.
3. We have many requests for `calc()`-less feature. We should mention `postcss-automath` in docs.

All this problems can be sold by separated Mathematics section. We could explicit tell that math is supported by all modern browsers. Users will see that PostCSS world cover math. And we could mention `postcss-automath` there.

**Comment by barraponto** [comment]
I guess users come to `precss` looking for support for Less/Sass, so I'd say it's better to just bundle `postcss-automath`...

**Comment by jonathantneal** [comment]
Answered by https://github.com/jonathantneal/precss/issues/98#issuecomment-359530222

And I’m open to a PR for the docs.
