### ISSUE TITLE
Is there a way to use precss in a synchronous way?

### ISSUE THREAD

**Issue by figalex** [jonathantneal/precss#92]
Right now I'm trying to use precss with [css-modules-require-hook](https://github.com/css-modules/css-modules-require-hook), which it has a way to include some PostCSS plugins but it only accepts sync plugins. When I try to include precss as a PostCSS plugin I get this error:

`Error: Use process(css).then(cb) to work with async plugins`

I'm not sure if the problem is that the [postcss-scss](https://github.com/postcss/postcss-scss) parser is async.

**Comment by jonathantneal** [comment]
Hmm. This just follows the plugin rules, so it can’t be responsible for being synchronous. I would redirect this to the postcss repo or the postcss chatroom on gitter. https://gitter.im/postcss/postcss
