### ISSUE TITLE
Any breaking change in v2.0?

### ISSUE THREAD

**Issue by tonytonyjan** [jonathantneal/precss#96]
The master branch has been v2.0 since a month ago, but I can't see a reminder in the changelog file, wondering if there is any breaking change.

**Comment by swrobel** [comment]
@jonathantneal please tag & update the Changelog, why the major version bump with no notes?

**Comment by volotovskyy** [comment]
@jonathantneal I have breaking change when tried to migrate from ^1.4.0 to v2.0 :(

I'm working on React SSR app with css-modules and postcss (precss for scss features).
We have webpack ^3.3.0 and some out of date `postcss.config.js` to provide postcss plugins and their options.

When I'm running my project I get whole terminal of this errors:
![screenshot 2017-11-03 17 04 37](https://user-images.githubusercontent.com/13667038/32380600-1d803d1c-c0b9-11e7-9cd1-33b721460156.png)

my `postcss.config.js`:

```
const path = require('path');

const staticPath = path.resolve(__dirname, './static');
const AUTOPREFIXER_BROWSERS = [
  'Android 2.3',
  'Android >= 4',
  'Chrome >= 35',
  'Firefox >= 31',
  'Explorer >= 10',
  'iOS >= 7',
  'Opera >= 12',
  'Safari >= 7.1',
];

module.exports = {
  plugins: [
    require('postcss-import')({
      // addDependencyTo: webpack,
      path: [
        `${process.cwd()}/src/styles/`,
        `${process.cwd()}/src/components/`
      ],
    }),
    require('precss')(),
    require('rucksack-css')(),
    require('postcss-calc')({
      mediaQueries: true
    }),
    require('postcss-color-function')(),
    require('postcss-inline-svg')({
      path: path.join(staticPath, 'icons', 'inline'),
    }),
    require('postcss-svgo'),
    require('autoprefixer')({
      browsers: AUTOPREFIXER_BROWSERS
    }),
  ]
};
```

Also this piece of `webpack.dev.config` may be helpful:
```
    rules: [
      {
        test: /\.scss$/,
        use: [
              'style-loader',
              { loader: 'css-loader', query: { modules: true, importLoaders: 2, sourceMap: true, localIdentName: '[name]_[local]_[hash:base64:5]' } },
              { loader: 'postcss-loader' }
            ]
      },
      { test: /\.css$/, loader: 'css-loader' },
```

SSR config is disabled for dev env so I guess no need to provide it now.

**Comment by jonathantneal** [comment]
Hey, I’m sorry for the lack of responses. I stepped away from this project, but recently I got pinged about how many people are still trying to use it, so today I decided to return to it.

I’ve rewritten the entire thing, and I’m looking to get it pushed into precss before the New Year.

**Comment by jonathantneal** [comment]
v2 did not have tested breaking changes, but v3 has many breaking changes.

Here is a list of the major updates:
https://github.com/jonathantneal/precss/blob/master/CHANGELOG.md
